name: Pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.15.7 ]
        os: [ ubuntu-20.04 ]
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/cache@v2
        with:
          path: vendor/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: |
          go mod vendor
          scripts/project.sh lint
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.15.7 ]
        os: [ ubuntu-20.04 ]
    name: Test
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/cache@v2
        with:
          path: vendor/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: |
          go mod vendor
          scripts/project.sh test
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.15.7 ]
        os: [ ubuntu-20.04 ]
    name: Build
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/cache@v2
        with:
          path: vendor/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: |
          go mod vendor
          scripts/project.sh build
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build/*
            !build/.gitkeep
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.15.7 ]
        os: [ ubuntu-20.04 ]
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Release
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build/
      - run: scripts/project.sh release
